import { ArrowDown, ArrowRight, BrainCircuit, Boxes, Database, Github, Layers3, Network, ScanSearch, Server, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";

type LayerProps = { icon: React.ReactNode; eyebrow: string; title: string; description: string; children?: React.ReactNode };

function Layer({ icon, eyebrow, title, description, children }: LayerProps) {
  return <section className="ci-surface rounded-2xl border p-5 shadow-sm sm:p-6"><div className="flex items-start gap-4"><div className="ci-empty-icon grid size-11 shrink-0 place-items-center rounded-xl text-white">{icon}</div><div className="min-w-0 flex-1"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">{eyebrow}</p><h2 className="mt-1 text-lg font-extrabold tracking-tight sm:text-xl">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p>{children}</div></div></section>;
}
function FlowArrow() { return <div className="flex justify-center py-2 text-primary"><div className="flex flex-col items-center"><div className="h-5 w-px bg-border"/><ArrowDown size={18}/></div></div>; }
function MiniCard({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <div className="ci-interactive rounded-xl border bg-background/70 p-4"><div className="flex items-center gap-2 text-sm font-bold">{icon}{title}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{text}</p></div>; }

export default function LandingPage() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b border-border bg-background/90 px-4 py-4 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="ci-empty-icon grid size-9 shrink-0 place-items-center rounded-lg text-white"><Network size={18}/></div><div><p className="font-extrabold">Codebase Intelligence</p><p className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">AI-powered codebase understanding</p></div></div><Link href="/dashboard" className="ci-ai-action inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-white shadow-sm">Open workspace <ArrowRight size={14}/></Link></div></header>
    <main className="mx-auto max-w-6xl p-4 sm:p-6 md:p-8">
      <div className="mb-8 overflow-hidden rounded-3xl ci-empty-state p-7 sm:p-10 md:p-14"><div className="max-w-3xl"><p className="font-mono text-[10px] font-bold uppercase tracking-[.24em] text-indigo-200">Developer intelligence platform</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl">Understand any codebase. <span className="text-indigo-200">Ship with confidence.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-indigo-100 sm:text-base">Connect a public GitHub repository and turn its source code into architecture, dependency, risk, security, quality and engineering intelligence.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/dashboard" className="ci-empty-action inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-extrabold">Analyze a repository <ArrowRight size={17}/></Link><a href="#workflow" className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-bold text-white hover:bg-white/15">See how it works <ArrowDown size={16}/></a></div></div></div>
      <div className="mb-8 grid gap-3 sm:grid-cols-3"><MiniCard title="Input" text="Public GitHub repository URL" icon={<Github size={15}/>} /><MiniCard title="Intelligence" text="Static analysis, graph and AI-assisted reasoning" icon={<BrainCircuit size={15}/>} /><MiniCard title="Output" text="Interactive engineering workspace" icon={<Sparkles size={15}/>} /></div>
      <div id="workflow" className="mb-7 text-center"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">End-to-end workflow</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">From repository to engineering intelligence</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">A transparent pipeline that keeps the repository as the source of truth while turning raw code into actionable insights.</p></div>
      <div className="mx-auto max-w-4xl">
        <Layer icon={<Github size={21}/>} eyebrow="1 · Input" title="GitHub Repository" description="Provide a public GitHub repository URL. The repository remains the source of truth for every analysis result."><div className="mt-4 rounded-xl border border-border bg-background/70 p-3 font-mono text-xs">https://github.com/owner/repository</div></Layer>
        <FlowArrow/>
        <Layer icon={<ScanSearch size={21}/>} eyebrow="2 · Ingestion" title="Repository Scanner & Indexer" description="The backend reads the repository, indexes source files, identifies languages, extracts imports, and builds the analysis dataset."><div className="mt-4 grid gap-3 sm:grid-cols-3"><MiniCard title="Clone / read" text="Load repository contents safely for analysis." icon={<Github size={15}/>} /><MiniCard title="File index" text="Catalog files, languages, lines and symbols." icon={<Database size={15}/>} /><MiniCard title="Dependency map" text="Resolve imports and relationships between modules." icon={<Network size={15}/>} /></div></Layer>
        <FlowArrow/>
        <Layer icon={<Layers3 size={21}/>} eyebrow="3 · Analysis engine" title="Code Analysis Engine" description="The indexed code is processed by multiple analyzers that produce structured engineering findings."><div className="mt-4 grid gap-3 sm:grid-cols-2"><MiniCard title="Architecture analyzer" text="Identifies application structure, modules and dependency relationships." icon={<Network size={15}/>} /><MiniCard title="Security analyzer" text="Looks for security-related risks and suspicious patterns." icon={<ShieldCheck size={15}/>} /><MiniCard title="Quality analyzer" text="Evaluates complexity, large files and maintainability signals." icon={<Boxes size={15}/>} /><MiniCard title="Risk analyzer" text="Prioritizes findings by severity and potential impact." icon={<ScanSearch size={15}/>} /></div></Layer>
        <FlowArrow/>
        <Layer icon={<BrainCircuit size={21}/>} eyebrow="4 · Intelligence" title="Codebase Intelligence Layer" description="Analysis results are converted into higher-level engineering insights for fast understanding and decision-making."><div className="mt-4 grid gap-3 sm:grid-cols-2"><MiniCard title="Security insights" text="Security score, findings and review priorities." icon={<ShieldCheck size={15}/>} /><MiniCard title="Code quality" text="Quality signals and complexity hotspots." icon={<Boxes size={15}/>} /><MiniCard title="Technical debt" text="Debt score based on risks, complexity and large files." icon={<Layers3 size={15}/>} /><MiniCard title="AI assistant" text="Natural-language questions about architecture, risks and dependencies." icon={<Sparkles size={15}/>} /></div></Layer>
        <FlowArrow/>
        <Layer icon={<Server size={21}/>} eyebrow="5 · Application API" title="API Server" description="The backend exposes analyzed repository data to the frontend through overview, files, risks, activity, graph and source-inspection APIs."><div className="mt-4 rounded-xl border border-border bg-background/70 p-4"><div className="flex flex-wrap items-center justify-center gap-2 text-[11px] font-mono"><span className="rounded-md bg-background px-2 py-1">/repository/overview</span><span className="rounded-md bg-background px-2 py-1">/repository/files</span><span className="rounded-md bg-background px-2 py-1">/repository/risks</span><span className="rounded-md bg-background px-2 py-1">/repository/graph</span><span className="rounded-md bg-background px-2 py-1">/repository/file/:path</span></div></div></Layer>
        <FlowArrow/>
        <Layer icon={<Sparkles size={21}/>} eyebrow="6 · Output" title="React Intelligence Dashboard" description="The frontend turns analysis into an interactive workspace where developers can inspect, navigate and prioritize the codebase."><div className="mt-4 grid gap-3 sm:grid-cols-2"><MiniCard title="Overview" text="Health score, repository metrics and priority risks." icon={<Boxes size={15}/>} /><MiniCard title="Dependency graph" text="Explore real repository dependencies and connected modules." icon={<Network size={15}/>} /><MiniCard title="Risk register" text="Review prioritized findings and affected source files." icon={<ShieldCheck size={15}/>} /><MiniCard title="Ask your codebase" text="Explore the repository through natural-language questions." icon={<BrainCircuit size={15}/>} /></div></Layer>
        <div className="mt-7 rounded-2xl border border-primary/20 bg-primary/5 p-6 text-center"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Ready to explore?</p><p className="mt-2 text-sm font-bold leading-7">GitHub Repository → Scanner → Analysis Engine → Intelligence Layer → API → Developer Workspace</p><Link href="/dashboard" className="ci-ai-action mt-5 inline-flex items-center gap-2 rounded-xl px-5 py-3 text-xs font-bold text-white">Start repository analysis <ArrowRight size={15}/></Link></div>
      </div>
    </main>
  </div>;
}
