import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { Activity, AlertTriangle, BarChart3, CheckCircle2, ExternalLink, FileCode2, GitBranch, LoaderCircle, Menu, Network, RefreshCw, Search, ShieldAlert, Sparkles, TrendingUp, X } from "lucide-react";

type Risk = "high" | "medium" | "low";
type FileItem = { path: string; name: string; directory: string; language: string; lines: number; complexity: number; risk: Risk; riskLabel: string; summary: string; importsCount: number; importedByCount: number };
type Overview = { projectName: string; repoUrl: string; scannedAt: string; totalFiles: number; totalModules: number; totalDependencies: number; healthScore: number; riskCount: number; languageBreakdown: Array<{ language: string; files: number; percentage: number }> };
type Detail = FileItem & { imports: string[]; importedBy: string[]; symbols: string[]; excerpt: string; content: string };
type Graph = { nodes: Array<{ id: string; label: string; path: string; directory: string; language: string; lines: number; imports: number; importedBy: number; risk: Risk }>; edges: Array<{ source: string; target: string; kind: string }> };
type Finding = { id: string; severity: Risk; title: string; detail: string; file: string; impact: string; relatedFiles: string[] };
type EventItem = { id: string; title: string; detail: string; timestamp: string; type: string };

const api = async <T,>(url: string, options?: RequestInit): Promise<T> => { const response = await fetch(`/api${url}`, { headers: { "Content-Type": "application/json" }, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body as T; };
function RiskBadge({ risk }: { risk: Risk }) { const styles = { high: "border-rose-200 bg-rose-50 text-rose-700", medium: "border-amber-200 bg-amber-50 text-amber-700", low: "border-emerald-200 bg-emerald-50 text-emerald-700" }; return <span className={`rounded-md border px-2 py-1 font-mono text-[10px] uppercase tracking-wider ${styles[risk]}`}>{risk}</span>; }
function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className="rounded-xl border border-border bg-card p-5 shadow-sm"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-4 font-mono text-3xl tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>; }
function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="rounded-xl border border-rose-200 bg-rose-50 p-8 text-center"><AlertTriangle className="mx-auto mb-3 text-rose-600" size={24} /><p className="font-semibold text-rose-900">We could not load this analysis</p><p className="mx-auto mt-2 max-w-xl text-sm text-rose-700">{message}</p>{onRetry && <button onClick={onRetry} className="mt-4 rounded-lg bg-rose-700 px-4 py-2 text-xs font-bold text-white">Try again</button>}</div>; }

export default function RepositoryDashboard() {
  const [location, navigate] = useLocation();
  const [repoUrl, setRepoUrl] = useState(""); const [overview, setOverview] = useState<Overview | null>(null); const [files, setFiles] = useState<FileItem[]>([]); const [risks, setRisks] = useState<Finding[]>([]); const [activity, setActivity] = useState<EventItem[]>([]); const [graph, setGraph] = useState<Graph | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [riskFilter, setRiskFilter] = useState("all"); const [languageFilter, setLanguageFilter] = useState("all"); const [selectedFile, setSelectedFile] = useState<Detail | null>(null); const [fileLoading, setFileLoading] = useState(false); const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const refresh = async () => { setError(""); if (!overview) return; try { const [o, f, r, a, g] = await Promise.all([api<Overview>("/repository/overview"), api<FileItem[]>("/repository/files?limit=5000"), api<Finding[]>("/repository/risks"), api<EventItem[]>("/repository/activity"), api<Graph>("/repository/graph")]); setOverview(o); setFiles(f); setRisks(r); setActivity(a); setGraph(g); setRepoUrl(o.repoUrl); } catch (e) { setError(e instanceof Error ? e.message : "Unable to refresh analysis"); } };
  useEffect(() => { api<Overview>("/repository/overview").then((o) => { setOverview(o); setRepoUrl(o.repoUrl); return refresh(); }).catch(() => {}); }, []);
  useEffect(() => { setMobileMenuOpen(false); }, [location]);
  const scan = async () => { setError(""); setMessage(""); if (!repoUrl.trim()) { setError("Paste a public GitHub repository URL first."); return; } setLoading(true); try { const result = await api<{ projectName: string }>("/repository/scan", { method: "POST", body: JSON.stringify({ repoUrl }) }); setMessage(`Analyzed ${result.projectName}.`); const [o, f, r, a, g] = await Promise.all([api<Overview>("/repository/overview"), api<FileItem[]>("/repository/files?limit=5000"), api<Finding[]>("/repository/risks"), api<EventItem[]>("/repository/activity"), api<Graph>("/repository/graph")]); setOverview(o); setFiles(f); setRisks(r); setActivity(a); setGraph(g); setRepoUrl(o.repoUrl); navigate("/"); } catch (e) { setError(e instanceof Error ? e.message : "Repository scan failed"); } finally { setLoading(false); } };
  const openFile = async (file: FileItem) => { setFileLoading(true); setError(""); try { setSelectedFile(await api<Detail>(`/repository/file/${file.path.split("/").map(encodeURIComponent).join("/")}`)); } catch (e) { setError(e instanceof Error ? e.message : "Could not open file"); } finally { setFileLoading(false); } };
  const languages = useMemo(() => [...new Set(files.map((file) => file.language))].sort(), [files]); const filteredFiles = useMemo(() => files.filter((file) => (!search || `${file.path} ${file.summary}`.toLowerCase().includes(search.toLowerCase())) && (riskFilter === "all" || file.risk === riskFilter) && (languageFilter === "all" || file.language === languageFilter)), [files, search, riskFilter, languageFilter]);
  const page = location === "/files" ? "files" : location === "/graph" ? "graph" : location === "/risks" ? "risks" : location === "/activity" ? "activity" : "overview";
  const nav = [["/", "Overview", BarChart3], ["/graph", "Dependency graph", GitBranch], ["/impact", "Impact Analysis", GitBranch], ["/files", "Files", FileCode2], ["/risks", "Risk register", ShieldAlert], ["/activity", "Activity", Activity]] as const;
  const aiNav = [["/insights", "AI Insights", Sparkles], ["/search", "Code Search", Search]] as const;
  const engNav = [["/engineering", "Engineering Intelligence", TrendingUp]] as const;

  return <div className="min-h-screen min-w-0 bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-50 border-r border-sidebar-border bg-sidebar text-sidebar-foreground transition-all duration-200 lg:translate-x-0 ${mobileMenuOpen ? "translate-x-0" : "-translate-x-full"} ${sidebarCollapsed ? "lg:w-[76px]" : "lg:w-[270px]"} w-[280px]`}>
      <div className={`flex h-[74px] items-center border-b border-sidebar-border ${sidebarCollapsed ? "justify-center px-3" : "gap-3 px-5"}`}><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><Network size={18} /></div>{!sidebarCollapsed && <div className="min-w-0"><div className="font-extrabold text-white">Codebase</div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-slate-400">intelligence</div></div>}<button onClick={() => { setMobileMenuOpen(false); setSidebarCollapsed((v) => !v); }} className={`${sidebarCollapsed ? "absolute -right-3 top-5" : "ml-auto"} grid size-9 place-items-center rounded-lg border border-sidebar-border bg-sidebar-accent text-slate-300 shadow-lg hover:bg-slate-700 hover:text-white`} aria-label={sidebarCollapsed ? "Expand navigation" : "Collapse navigation"} title={sidebarCollapsed ? "Expand navigation" : "Collapse navigation"}><Menu size={18}/></button><button onClick={() => setMobileMenuOpen(false)} className="ml-auto rounded-lg p-2 text-slate-400 hover:bg-sidebar-accent hover:text-white lg:hidden" aria-label="Close navigation"><X size={18}/></button></div>
      <div className="overflow-y-auto p-4" style={{ height: "calc(100vh - 74px)" }}>
        {!sidebarCollapsed && <p className="mb-3 px-3 font-mono text-[10px] uppercase tracking-widest text-slate-500">Workspace</p>}
        {nav.map(([href, label, Icon]) => <Link key={href} href={href} onClick={() => setMobileMenuOpen(false)} title={sidebarCollapsed ? label : undefined} className={`mb-1 flex items-center rounded-lg py-2.5 text-sm font-semibold ${sidebarCollapsed ? "justify-center px-2" : "gap-3 px-3"} ${page === (href === "/" ? "overview" : href.slice(1)) ? "bg-sidebar-accent text-white" : "text-slate-400 hover:bg-sidebar-accent hover:text-white"}`}><Icon size={16}/>{!sidebarCollapsed && label}</Link>)}
        {!sidebarCollapsed && <><p className="mb-3 mt-6 px-3 font-mono text-[10px] uppercase tracking-widest text-slate-500">Intelligence</p>{aiNav.map(([href, label, Icon]) => <Link key={href} href={href} onClick={() => setMobileMenuOpen(false)} className="mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-400 hover:bg-sidebar-accent hover:text-white"><Icon size={16}/>{label}</Link>)}<p className="mb-3 mt-6 px-3 font-mono text-[10px] uppercase tracking-widest text-slate-500">Engineering</p>{engNav.map(([href, label, Icon]) => <Link key={href} href={href} onClick={() => setMobileMenuOpen(false)} className="mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-400 hover:bg-sidebar-accent hover:text-white"><Icon size={16}/>{label}</Link>)}</>}
        {!sidebarCollapsed && <div className="mt-6 rounded-xl border border-sidebar-border bg-slate-800/70 p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-slate-500">Current repository</p><p className="mt-2 truncate font-mono text-xs text-slate-200">{overview?.projectName || "No repository"}</p><p className="mt-1 text-[11px] text-slate-500">{overview ? "Public GitHub · read-only" : "Paste a GitHub URL to begin"}</p></div>}
      </div>
    </aside>
    {mobileMenuOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-40 bg-slate-950/50 lg:hidden" onClick={() => setMobileMenuOpen(false)} />}
    <main className="min-w-0 flex-1 transition-[margin] duration-200 lg:ml-[270px]" style={{ marginLeft: typeof window !== "undefined" && window.innerWidth >= 1024 && sidebarCollapsed ? 76 : undefined }}>
      <header className="sticky top-0 z-30 border-b border-border bg-background/95 px-4 py-3 backdrop-blur sm:px-5 sm:py-4 md:px-8"><div className="mx-auto max-w-[1500px]"><div className="mb-3 flex items-center gap-2 lg:hidden"><button onClick={() => setMobileMenuOpen(true)} className="grid size-10 shrink-0 place-items-center rounded-lg border border-border bg-card text-muted-foreground" aria-label="Open navigation"><Menu size={19}/></button><div className="min-w-0"><p className="truncate text-sm font-extrabold">Codebase Intelligence</p><p className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">Repository analyzer</p></div></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-2 rounded-lg border border-border bg-card px-3"><GitBranch size={15} className="shrink-0 text-muted-foreground"/><input value={repoUrl} onChange={(e) => setRepoUrl(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") void scan(); }} placeholder="https://github.com/owner/repository" className="min-w-0 flex-1 bg-transparent py-3 text-xs outline-none sm:text-sm"/><button onClick={() => void scan()} disabled={loading} className="inline-flex shrink-0 items-center gap-2 rounded-md bg-primary px-3 py-2 text-[11px] font-bold text-primary-foreground disabled:opacity-60 sm:px-4 sm:text-xs">{loading ? <LoaderCircle size={14} className="animate-spin"/> : <Search size={14}/>}<span className="hidden xs:inline">{loading ? "Analyzing" : "Analyze repository"}</span><span className="xs:hidden">{loading ? "Analyzing" : "Analyze"}</span></button></div><button onClick={() => void refresh()} disabled={!overview || loading} className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-border bg-card px-3 py-2.5 text-xs font-bold text-muted-foreground disabled:opacity-50 sm:w-auto"><RefreshCw size={14}/> Refresh</button></div></div></header>
      <div className="mx-auto max-w-[1500px] p-4 sm:p-5 md:p-8">
        {!overview && !loading && <section className="mb-8 rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8 md:p-12"><div className="max-w-3xl"><p className="mb-3 font-mono text-[10px] uppercase tracking-[.2em] text-emerald-700">Repository analyzer</p><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl md:text-5xl">Understand any public GitHub codebase.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Paste a repository URL above. The backend clones it read-only, indexes source files, maps imports, detects code risks, and exposes the results through this dashboard.</p><div className="mt-7 flex flex-wrap gap-3 text-xs font-semibold"><span className="rounded-lg bg-muted px-3 py-2">📁 File inventory</span><span className="rounded-lg bg-muted px-3 py-2">🕸 Dependency graph</span><span className="rounded-lg bg-muted px-3 py-2">⚠️ Risk detection</span><span className="rounded-lg bg-muted px-3 py-2">🔎 Source inspection</span></div></div></section>}
        {error && <div className="mb-6"><ErrorState message={error} onRetry={overview ? refresh : undefined}/></div>}{message && <div className="mb-6 flex items-start gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 size={16} className="mt-0.5 shrink-0"/>{message}</div>}
        {overview && <><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div className="min-w-0"><p className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground">Repository overview</p><h1 className="truncate text-2xl font-extrabold tracking-tight sm:text-3xl md:text-4xl">{overview.projectName}</h1><a href={overview.repoUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1.5 truncate text-xs font-semibold text-primary hover:underline"><span className="truncate">{overview.repoUrl}</span><ExternalLink size={12} className="shrink-0"/></a></div><div className="font-mono text-[10px] text-muted-foreground">Last scan {new Date(overview.scannedAt).toLocaleString()}</div></div>{page === "overview" && <OverviewView overview={overview} risks={risks} files={files}/>} {page === "files" && <FilesView files={filteredFiles} allFiles={files} search={search} setSearch={setSearch} riskFilter={riskFilter} setRiskFilter={setRiskFilter} languageFilter={languageFilter} setLanguageFilter={setLanguageFilter} languages={languages} onOpen={openFile}/>} {page === "graph" && <GraphView graph={graph} onOpen={(path) => { const file = files.find((f) => f.path === path); if (file) void openFile(file); }}/>} {page === "risks" && <RisksView risks={risks} onOpen={(path) => { const file = files.find((f) => f.path === path); if (file) void openFile(file); }}/>} {page === "activity" && <ActivityView activity={activity}/>}</>}
      </div>
    </main>
    {(selectedFile || fileLoading) && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-2 sm:p-4" onClick={() => !fileLoading && setSelectedFile(null)}><div className="flex max-h-[96vh] w-full max-w-6xl flex-col overflow-hidden rounded-xl border border-border bg-card shadow-2xl sm:max-h-[92vh] sm:rounded-2xl" onClick={(e) => e.stopPropagation()}>{fileLoading ? <div className="p-12 text-center text-sm text-muted-foreground">Loading source…</div> : selectedFile && <><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="font-mono text-xs text-muted-foreground">{selectedFile.language} · {selectedFile.lines} lines</p><h2 className="font-bold">{selectedFile.path}</h2></div><button onClick={() => setSelectedFile(null)} className="rounded-lg p-2 hover:bg-muted"><X size={18}/></button></div><pre className="max-h-[70vh] overflow-auto p-5 text-xs leading-6"><code>{selectedFile.content}</code></pre></>}</div></div>}
  </div>;
}

function OverviewView({ overview, risks, files }: { overview: Overview; risks: Finding[]; files: FileItem[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Files" value={overview.totalFiles} note="Indexed source files"/><Metric label="Dependencies" value={overview.totalDependencies} note="Detected relationships"/><Metric label="Health" value={`${overview.healthScore}/100`} note="Repository health score"/><Metric label="Risks" value={risks.length} note="Detected findings"/><div className="md:col-span-2 xl:col-span-4 rounded-xl border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Repository signals</h2><p className="text-xs text-muted-foreground">Highest-risk files from the current scan.</p></div></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{files.slice(0, 6).map((file) => <div key={file.path} className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{file.path}</span><RiskBadge risk={file.risk}/></div><p className="mt-2 text-xs text-muted-foreground">{file.lines} lines · complexity {file.complexity}</p></div>)}</div></div></div>; }
function FilesView({ files, allFiles, search, setSearch, riskFilter, setRiskFilter, languageFilter, setLanguageFilter, languages, onOpen }: any) { return <section className="rounded-xl border border-border bg-card p-5"><div className="mb-5 flex flex-col gap-3 lg:flex-row"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search files…" className="flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none"/><select value={riskFilter} onChange={(e) => setRiskFilter(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="all">All risks</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={languageFilter} onChange={(e) => setLanguageFilter(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="all">All languages</option>{languages.map((l: string) => <option key={l}>{l}</option>)}</select></div><p className="mb-3 text-xs text-muted-foreground">Showing {files.length} of {allFiles.length} files</p><div className="divide-y divide-border">{files.map((file: FileItem) => <button key={file.path} onClick={() => onOpen(file)} className="flex w-full items-center justify-between gap-4 px-2 py-3 text-left hover:bg-muted/50"><div className="min-w-0"><p className="truncate text-sm font-semibold">{file.path}</p><p className="text-xs text-muted-foreground">{file.language} · {file.lines} lines · {file.importsCount} imports</p></div><RiskBadge risk={file.risk}/></button>)}</div></section>; }
function GraphView({ graph }: { graph: Graph | null; onOpen: (path: string) => void }) { return <section className="rounded-xl border border-border bg-card p-8"><h2 className="font-bold">Dependency graph</h2><p className="mt-2 text-sm text-muted-foreground">{graph?.nodes.length ?? 0} nodes · {graph?.edges.length ?? 0} relationships detected. Open the full graph from the sidebar.</p></section>; }
function RisksView({ risks, onOpen }: { risks: Finding[]; onOpen: (path: string) => void }) { return <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 font-bold">Risk register</h2><div className="space-y-3">{risks.map((risk) => <button key={risk.id} onClick={() => onOpen(risk.file)} className="block w-full rounded-xl border border-border p-4 text-left hover:bg-muted/40"><div className="flex items-center justify-between gap-3"><span className="font-semibold">{risk.title}</span><RiskBadge risk={risk.severity}/></div><p className="mt-2 text-xs text-muted-foreground">{risk.file} · {risk.detail}</p></button>)}</div></section>; }
function ActivityView({ activity }: { activity: EventItem[] }) { return <section className="rounded-xl border border-border bg-card p-5"><h2 className="mb-4 font-bold">Activity</h2><div className="space-y-3">{activity.map((item) => <div key={item.id} className="rounded-lg border border-border p-3"><p className="font-semibold text-sm">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.detail} · {new Date(item.timestamp).toLocaleString()}</p></div>)}</div></section>; }
